### ISSUE TITLE
Import Job for Opportunity Data from beta.sam

### ISSUE THREAD

**Issue by recro-lataille** [recro/medulla#10]
## Is your feature request related to a problem? Please describe.
In the system we need to have all current opportunities and past awards so that we can correlate the data

## Describe the solution you'd like
Beta.sam posts CSV's daily and has historic postings as well. we will need to bulk import the historic data going back 5 years if possible. WE will also want award data.  https://sam.gov/data-services/Contract%20Opportunities?privacy=Public

## Describe alternatives you've considered
could look at other ways to pull the data

## Additional context
it would be great to find a way to correlate the previous award data to the current opportunities to come up with a list of companies with a high chance of pursuit.

**Comment by AndrewBabbitt97** [comment]
Issues such as this will be tracked separately from now on in their own project.
