### ISSUE TITLE
Ability to search opportunities, create triggers for new opportunities

### ISSUE THREAD

**Issue by recro-lataille** [recro/medulla#11]
## Is your feature request related to a problem? Please describe.
Users need to be able to search the opportunities in the system and implement filters for things like full open or small business set-a-sides. this search should include full text search of the documents the government has attached to an opportunity, Users should be able to save searches and also get notified (through email or text or an internal alert in the system when an opportunity matches there criteria. they should also be able to automatically add opportunities matching there criteria into a pipeline

## Describe the solution you'd like
search page with filters, advanced search page, the ability to save a search and the ability to activate alerts when new opportunities matching there search appear.

## Describe alternatives you've considered
none

**Comment by AndrewBabbitt97** [comment]
Issues such as this will be tracked separately from now on in their own project.
