### ISSUE TITLE
Oppertunity/Deal tracking

### ISSUE THREAD

**Issue by recro-lataille** [recro/medulla#13]
## Is your feature request related to a problem? Please describe.
Opportunities (Deals) are a key component of CRM they are unique items moving through a pipeline. different orgs will have different needs

## Describe the solution you'd like
Users should be able to create opportunities, users should be able to associate an opportunity to one or more companies, users should be able to associate contacts to opportunities, opportunities should have a state on a pipeline. users should be able to log notes, create tasks, log meetings, phone calls and emails to specific opportunities. these logs could also be associated with other opportunities. 

fields for opportunities - name, description, value, companies(association to company's in the system), contacts (association to contacts in the system), assigned to (association to the organizations users) could be one or multiple. custom fields created by an organization for deals (custom deal properties). This is all very much hub-spot

## Additional context

![Screenshot 2021-09-09 5 36 48 PM](https://user-images.githubusercontent.com/43007015/132765908-84647e3a-8ae1-4996-91ac-e4cf951075c4.png)

![Screenshot 2021-09-09 5 39 35 PM](https://user-images.githubusercontent.com/43007015/132766152-4a813224-383c-403d-b321-0f941e282446.png)

**Comment by AndrewBabbitt97** [comment]
Issues such as this will be tracked separately from now on in their own project.
