### ISSUE TITLE
Kubernetes Controller

### ISSUE THREAD

**Issue by AndrewBabbitt97** [recro/medulla#138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

We need an interaction layer with Kubernetes, this should likely be done as a Kubernetes controller so that we can interact with CRDs and follow the operator pattern.

### Describe the solution you'd like

We need to get the existing KubeOps branch merged into main, this branch contains some database CRDs and work.

### Additional context

On top of getting the branch mergable, we should add an Application CRD as well. This should contain the following fields:

- Application Name
- Application Description

**Comment by keithlogan94** [comment]
Waiting for pull request to get merged, need to fix issues with Andrews review.

**Comment by keithlogan94** [comment]
@AndrewBabbitt97 please review the merge request in progress again.
