### ISSUE TITLE
Contacts/company Management

### ISSUE THREAD

**Issue by recro-lataille** [recro/medulla#14]
## Is your feature request related to a problem? Please describe.
Contacts are needed to associate to deals so you know who to work with

## Describe the solution you'd like
Users should be able to import there contacts from google/apple/outlook. they should also be able to add contact manually. the users email address should be used to associate them to companies. companies should be able to be added/edited manually. if someone imports contact the company info would be mostly blank we would create a company that has the name of the companies URL minus the top-level domain, we should grab the company page thumbnail from there site when they are added. 

core fields for contacts

Name, Primary Phone, Email, date added, (organizations should be able to customize additional fields)

Core fields for companies
Name, Domain, (organizations should be able to customize additional fields)

Association when deals are added associated to a company you should be able to see this from the company page. when deals are added associated with a contact you should see them from the contacts page. when other things are logged with associations to either they should appear on the page for that association (see screen shots) 

## Additional context

![Screenshot 2021-09-09 5 49 32 PM](https://user-images.githubusercontent.com/43007015/132767248-da158cd1-3da9-413c-92be-e67769f83981.png)
![Screenshot 2021-09-09 5 50 06 PM](https://user-images.githubusercontent.com/43007015/132767267-1bdb8bd0-2143-4069-8702-e563bfb91e1b.png)
![Screenshot 2021-09-09 5 51 03 PM](https://user-images.githubusercontent.com/43007015/132767351-fbdb429d-d100-4b10-bd2f-5ee791019f2e.png)

**Comment by AndrewBabbitt97** [comment]
Issues such as this will be tracked separately from now on in their own project.
