### ISSUE TITLE
Standup Meetings Schedule

### ISSUE THREAD

**Issue by keithlogan94** [recro/medulla#157]
### Summary

Open Medulla project for current sprint https://github.com/orgs/recro/projects/3/views/2

Any updates on pull requests being merged.

#### These standup questions will be asked every standup, and recorded into the issue being worked on.
<br>

#### Status for [Team Member]
<b>What did you work on yesterday?</b>
`Team members status for yesterday for what has been completed.`
<b>What will you work on today?</b>
`Team members status for today, for what will be completed by end of today.`  
<b>Are there any blockers in your way?</b>
`Team member status on blockers, for anything that is blocking work.`
<b>Are we on track to complete the work by end of the sprint with the sprint goal?</b>
`Team members status on if work is on track to be completed by end of sprint.`
<b>Has a pull request been created and remote branches up to date?</b>
`Team members status on if pull request has been created and all work is pushed and up to date with remote branches.`
*Pull requests need to be created early, for early review, and to make sure work matches vision for ticket.*
        
        *Record answers into issue as comment.*

#### Optional Questions to ask everyone in standup
Is the ticket clear and understandable to work on? Do you think that you are working inline for the vision of the ticket?
Who could use some help? 
Who has some time available to help?
Any go backs?
Any questions, comments, or concerns?

### Motivation and goals

NA

### In scope

NA

### Out of scope

NA

### Risks / unknowns

NA

### Examples

NA

### Detailed design

NA

**Comment by AndrewBabbitt97** [comment]
Issue is not of an open source nature and should be restructured into an internal team doc.
