### ISSUE TITLE
Research and Demo a Low Code Platform Application 

### ISSUE THREAD

**Issue by babanfaraj** [recro/medulla#170]
### Summary

> Research and demo a low code platform application.

### Time Requirements
> This task is to be completed by Tuesday, 10AM MST.

### Acceptance Criteria

> Create a simple application in the Code Platform that you have chosen to work with. This will be demo'd.

> Create Word Document docx file that contains screenshots and detailed explanation of the following features of the low code platform

> Explain how feature is performed with screenshots for: UI Frontend Design & Component Drag drop with child relationships

> Explain how feature is performed with screenshots for: Database table design and foreign key constraints

> Explain how feature is performed with screenshots for: Actions like sending email on click of a button. Make sure to capture in the explanation how the the relationship is made between the UI, and an action on the backend.

> Anything that is interesting

> <b>Attach your word documents to this ticket as a comment when you are completed.</b>

**Comment by babanfaraj** [comment]
@dariuswatson : Mendix
@keithlogan94 : Microsoft Powerapps 
@devopkeith : N8n
@babanfaraj: Quixy 
@Slygecko : Nodered 

We will be looking into these low code platform applications to gather ideas that will be beneficial for Medulla,  and do a demo. This issue will take no longer than today.

**Comment by babanfaraj** [comment]
Quixy sometimes blocks the ability to create a data table and  data source and other features . Managed to get a screenshot of using it for a second but got blocked. Need to contact sales to do so.

**Comment by keithlogan94** [comment]
No problem, just do your best to explain if something isn't allowed or whatever other reason in the docx. Also, I'm using Google Docs and it allows exporting as a Docx.

**Comment by keithlogan94** [comment]
[PowerApps Overview.docx](https://github.com/recro/medulla/files/8996451/PowerApps.Overview.docx)

**Comment by keithlogan94** [comment]
[PowerApps Overview.pdf](https://github.com/recro/medulla/files/8996456/PowerApps.Overview.pdf)

**Comment by keithlogan94** [comment]
https://apps.powerapps.com/play/200187b2-651b-4e4c-a0fe-c51fb28d7690?tenantId=ae561c3c-0613-42e0-9d20-8c66c3a137f1

**Comment by devopkeith** [comment]
I'm still working on n8n.io. All of my OAuth tokens are failing. I was able to get appsmith working, which was really cool. n8n also looks really cool, I like their UI. 
[AppSmith-testapp.docx](https://github.com/recro/medulla/files/8997542/AppSmith-testapp.docx)

**Comment by babanfaraj** [comment]
[Quickly.pptx](https://github.com/recro/medulla/files/9002556/Quickly.pptx)
[Quickly.pdf](https://github.com/recro/medulla/files/9002557/Quickly.pdf)

PPTX slides contains little more comments if needed. PDF  has just the slides.

**Comment by babanfaraj** [comment]
[Quixy.pptx](https://github.com/recro/medulla/files/9002562/Quixy.pptx)
https://quixy.com/

**Comment by dariuswatson** [comment]
Attaching notes and UI screen shots for Mendix platform: 
[Mendix_Notes.docx](https://github.com/recro/medulla/files/9003001/Mendix_Notes.docx)

https://www.mendix.com/
