### ISSUE TITLE
Generic Storage Api

### ISSUE THREAD

**Issue by keithlogan94** [recro/medulla#171]
### Summary

> Write Grpc ProtoBuf file for Generic Storage Api

### Time Requirements
> This task is only to write the protobuf file which will be very simple. Should take 4 hours at most.

### Acceptance Criteria

> Protobuf file should have these functions

> SaveSerializedClass(string SerializedClass) : return uuid

> GetSerializedClass(string uuid)

> GetAllSerializedClasses() : returns all serialized strings List<string> 

> Should contain those 3 functions and the data messages to go with it

### User Story
> As a developer I want to serialize any class, and save it through this grpc api, and KubeOps will deserialize it and save it to a specific CRD

**Comment by AndrewBabbitt97** [comment]
Not needed now with move away from CRDs.
