### ISSUE TITLE
Generic Storage API Implementation

### ISSUE THREAD

**Issue by keithlogan94** [recro/medulla#172]
### Summary

> Implement Grpc Implementation for Generic Storage API

### Time Requirements
> 1-3 days

### Acceptance Criteria

> Any serialized class can be saved through a gRPC api to a generic storage CRD, KubeOps will take that generic storage CRD, and convert it into a specific Human Readable, Modifiable CRD based on the serialized class

> If someone updates the Human Readable, Modifiable CRD, KubeOps will update the generic storage serialized class CRD

> Users of the generic storage api should be able to get, list, save new, update, and delete generic storage CRDs which will update any specific CRD

### User Story
> As a developer I want to serialize any class, and save it through this grpc api, and KubeOps will deserialize it and save it to a specific CRD

**Comment by AndrewBabbitt97** [comment]
Not needed now due to removal of CRD's.
