### ISSUE TITLE
Generic Storage Api Frontend Page

### ISSUE THREAD

**Issue by keithlogan94** [recro/medulla#173]
### Summary

> Implement Frontend Page which lists all generic storage object, and allows modifying properties, saving, deleting, searching

### Time Requirements
> 1-3 days

### Acceptance Criteria

> Implement Frontend Page which lists all generic storage object, and allows modifying properties, saving, deleting, searching

> Should be able to search through all objects

> Should be able to modify an object's properties directly

> Should be able to go to the specific editor for an object, if an object is a page, then the user will be redirected to the page editor, if an object is a workflow, then the user will be redirected to the workflow editor for that object, same for database model

### User Story
> As a developer I want to serialize any class, and save it through this grpc api, and KubeOps will deserialize it and save it to a specific CRD

**Comment by AndrewBabbitt97** [comment]
Not needed now due to removal of KubeOps.
