### ISSUE TITLE
Create Definition of CRD in KubeOps for Generic Storage Object

### ISSUE THREAD

**Issue by keithlogan94** [recro/medulla#174]
### Summary

> Create Definition of CRD in KubeOps for Generic Storage Object

### Time Requirements
> 4 hours

### Acceptance Criteria

> CRD needs to be created in KubeOps for Generic Storage Object

> Generic Storage Object needs to be able to store any serialized class in C#

> This should have a string field to store the serialized C# class as a string

> do not try to store fields of a class separately, entire C# class needs to be serialized and stored in 1 field

> do not try to write the controller for this, this is only the CRD definition

> only other field on the CRD should be uuid string

### User Story
> As a developer I want to serialize any class, and save it through this grpc api, and KubeOps will deserialize it and save it to a specific CRD

**Comment by AndrewBabbitt97** [comment]
Closed due to removal of CRD's.
