### ISSUE TITLE
Create definition of CRD for Medulla Page

### ISSUE THREAD

**Issue by keithlogan94** [recro/medulla#175]
### Summary

> Create Definition of CRD in KubeOps for Medulla Page

### Time Requirements
> 4 hours

### Acceptance Criteria

> A Medulla page should be saved to a CRD

> The CRD should have a uuid property

> The CRD should have a string property which stores an html like structure of components, but don't define the structure, just provide a string property 

### User Story
> As a developer I want to save a page to Kubernetes

**Comment by AndrewBabbitt97** [comment]
Closed for not following issue template.
