### ISSUE TITLE
.

### ISSUE THREAD

**Issue by keithlogan94** [recro/medulla#177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

> Implement Frontend Page which lists all generic storage object, and allows modifying properties, saving, deleting, searching

### Time Requirements
> 1-3 days

### Acceptance Criteria

> Implement Frontend Page which lists all generic storage object, and allows modifying properties, saving, deleting, searching

> Should be able to search through all objects

> Should be able to modify an object's properties directly

> Should be able to go to the specific editor for an object, if an object is a page, then the user will be redirected to the page editor, if an object is a workflow, then the user will be redirected to the workflow editor for that object, same for database model

### User Story
> As a developer I want to serialize any class, and save it through this grpc api, and KubeOps will deserialize it and save it to a specific CRD

### Describe the solution you'd like

.

### Additional context

.

**Comment by AndrewBabbitt97** [comment]
Closed for not following issue template.
