### ISSUE TITLE
Write documentation on Medulla

### ISSUE THREAD

**Issue by keithlogan94** [recro/medulla#186]
Basic readme instructions for end users

**Comment by dariuswatson** [comment]
Created PR: Update documentation & update 404.html location #188
https://github.com/recro/medulla/pull/188

Changes:
- Update deploy-docs.yml to correct path for 404.html
- Update image path (high-level-architecture.png) and dependencies links within repository
- Start updating concepts documentation

**Comment by dariuswatson** [comment]
[previous PR 187](https://github.com/recro/medulla/pull/187)
