### ISSUE TITLE
As a Developer, I would like any container to be automatically built, and pushed into the Medulla ghcr (Github Container Registry) during the CICD process, so that containers can be auto built, and pulled from Kubernetes

### ISSUE THREAD

**Issue by keithlogan94** [recro/medulla#192]
### Summary

> As a Developer, I would like any container to be automatically built, and pushed into the Medulla ghcr (Github Container Registry) during the CICD process, so that containers can be auto built, and pulled from Kubernetes

### Time Requirements
> 1 day-2 days

### Acceptance Criteria

> When a repository is tagged with a semantic version 1.0.0 in the main branch, the build for containers should start

> Building should run tye build and publish to ghcr

> Use Github Actions to implement this

> Must comment on this ticket with your progress, and comments must be made that you approve of this ticket, and fully understand the ticket before starting it.

### User Story
> As a Developer, I would like any container to be automatically built, and pushed into the Medulla ghcr (Github Container Registry) during the CICD process, so that containers can be auto built, and pulled from Kubernetes

**Comment by AndrewBabbitt97** [comment]
Closed for not following issue template.
