### ISSUE TITLE
As a developer, I want a generic storage Grpc Api for saving any object to Kubernetes, so that I can save all objects as serialized strings, with a type identifier

### ISSUE THREAD

**Issue by keithlogan94** [recro/medulla#199]

**Comment by keithlogan94** [comment]
### Summary

> Build a generic storage api, for all Medulla object to save, list, get in Kubernetes

### Time Requirements
> 1 day-4 days

### Acceptance Criteria

> List, get, save generic objects to Kubernetes

**Comment by AndrewBabbitt97** [comment]
Closed for not following issue template.
