### ISSUE TITLE
Component Editor

### ISSUE THREAD

**Issue by babanfaraj** [recro/medulla#2]
## Summary
A user of Medulla should be able to create  a component within Medulla. Once the component has been designed by the user and the user saves it, an api request  (using GRPC) will be made to the corresponding endpoint within the backend. The request should contain the component the user made in a string format.

## Motivation and goals
This allows the user to create components, and save it by interacting with the backend. Doing so, allows future reuse of the component.

## In scope
Creating a component and attempting to save the component (only documenting and styling).

## Out of scope
Interactively of the components, confirmation of component storage.

## Risks / unknowns
There are currently no constraints in regards to creating components.

## Examples
A user creates a component by inserting a label and a button. Once the design of this component is saved, the user will save it. After it has been saved, an api request will be made to the corresponding endpoint to store this component.

**Comment by babanfaraj** [comment]
For now, we will have simple components with only HTML and CSS.

**Comment by babanfaraj** [comment]
I believe we need to approach this in the following order of work:

Medulla:
1.  Move previous code into the new front end framework we are using (Blazer)
2.  Figure out an alternative to grape.js
3.  Add the ability if not already implemented to create a component
4.  Implement a method to take the designed component from the user of Medulla to convert it into a string or another requested format for the backend to store the component.
5.  Implement a API request to send the component to the backend



@keithlogan94  @AndrewBabbitt97   thoughts on this order?

**Comment by babanfaraj** [comment]
I will start looking into Blazer and see how drag and drop works along with what components we can use for this.

**Comment by AndrewBabbitt97** [comment]
@babanfaraj Here's a good arrival on it, you use the standard HTML5 events for it: https://chrissainty.com/investigating-drag-and-drop-with-blazor/

**Comment by keithlogan94** [comment]
I like how we are commenting within these issues. It keeps conversations scoped to the work.

**Comment by babanfaraj** [comment]
> @babanfaraj Here's a good article on it, you use the standard HTML5 events for it: https://chrissainty.com/investigating-drag-and-drop-with-blazor/

Thank you @AndrewBabbitt97 ! I will look into this and try to create a sample program going so we can go from there. 

Once I figure out the jest of it, will there be a place in the front end for it @keithlogan94 ? I noticed you had the other pull request open for the start of the project
