### ISSUE TITLE
As a Medulla User, when I click on the Page editor from the dashboard, it will give me a form to fill out for a new page CRD, or it will ask me to edit an existing CRD, so that I can start editiing a page

### ISSUE THREAD

**Issue by keithlogan94** [recro/medulla#201]
### Summary

> Goal is to start editing a page, ask user if new page, or existing page,

### Time Requirements
> 1 day

### Acceptance Criteria

> If new page, then give form

> If existing page, then redirect to object browser

**Comment by AndrewBabbitt97** [comment]
Closed for not following issue template.
