### ISSUE TITLE
As a Developer, I want the object Id of the CRD to be in the Url as a url parameter on the Page Editor, and that object needs to be queried from the object storage api, and edited within the editor, so that the object browser can redirect to any editor with only a object id

### ISSUE THREAD

**Issue by keithlogan94** [recro/medulla#202]
### Summary

> In each editor, pull the object from the object storage api with an object id from url parameter

### Time Requirements
> 1 day

### Acceptance Criteria

> Retrive the object CRD from Kubernetes by the Id given in url param

> Do not need to save object back to editor, this task is just to pull the object from the backend from url param id

**Comment by AndrewBabbitt97** [comment]
Closed for not following issue template.
