### ISSUE TITLE
As a developer, I need a class that has string property for a docker image to run, and a link to another Action Class to run after completing, so that it has the basic fundamentals for an Action

### ISSUE THREAD

**Issue by keithlogan94** [recro/medulla#211]
### Summary

> Action class which can be deserialized and serialized to xml

### Time Requirements
> 1 day

### Acceptance Criteria

> Can be serialized, and deserialized to xml

> Has a link to another Action Class

> Has a Name

> Has a Description

> Has an Id

> Has a Run function which when it has access to Kubernetes, it will create a Pod on the cluster and run that docker image

**Comment by AndrewBabbitt97** [comment]
Closed for not following issue template.
