### ISSUE TITLE
File storage for user uploads

### ISSUE THREAD

**Issue by keithlogan94** [recro/medulla#24]
File storage for images, svgs, and other user uploads

The Medulla frontend editor needs static file storage which can save images, svgs and other user uploads, and be able to retrieve all those resources with a link which gets served over the appropriate mime Content-Type request header when requested.

**Comment by aijazsmartdata** [comment]
Hi @AndrewBabbitt97 ,

Where i have to save images ?

**Comment by aijazsmartdata** [comment]
There is any path ?

**Comment by AndrewBabbitt97** [comment]
@aijazsmartdata needs to be configurable from appsettings.json

**Comment by AndrewBabbitt97** [comment]
It will be saved into a kubernetes volume/path. So just to disk
